### ISSUE TITLE
Cuda 10.1

### ISSUE THREAD

**Issue by Amir-Arsalan** [NVIDIAGameWorks/FleX#100]
@mmacklin many libraries/packages depend on CUDA >= 10 these days and it's becoming harder and harder to compile them with older versions of CUDA. Would it be possible to release the solver binaries for newer versions of CUDA? I've been totally unable to run FleX after our cluster upgraded the drivers to 430.50. I can still compile FleX and only some of the other libraries with a Singularity container that has an older version of CUDA, but for some reason the driver upgrade makes FleX spit out errors when running despite successful compilation. I think it's necessary to be able to compile FleX with a newer version of CUDA.

Here are the errors I'm getting:

```
Flex: Could not open CUDA driver, ensure you have the latest driver (nvcuda.dll) installed and an NVIDIA GPU present on the system - ./../../../src/cuda/util.cpp:145
Flex: Could not initialize CUDA driver - ../../../src/cuda/flex.cu:4624
Could not initialize Flex, exiting.
```

**Comment by Spphire** [comment]
> This was caused due to an issue on our cluster but I still cannot compile FleX with new versions of CUDA unfortunately ...

can u use flex on cuda10+ now?
