### ISSUE TITLE
Flex Demo: cannot drag items

### ISSUE THREAD

**Issue by nrjenk** [NVIDIAGameWorks/FleX#113]
I've seen videos of this demo, and they can pick up the cloths in some simulations, but when I try, it doesn't work, I can only modify settings but cannot otherwise interact with them. I've tried on my laptop with an NVIDIA GPU and on my PC with an AMD GPU, both it didn't work. I don't know if there's something I'm missing or it was just a feature of an older version, but I tried on an older version too.

**Comment by Trystanr** [comment]
You use a combination of shift + left mouse to drag particles as stated in the README.

**Comment by nrjenk** [comment]
thanks
